### PR TITLE
Bigint fixes take 2

### PR DESCRIPTION
**Pull request by weltling**
Checked/fixed pdo_mysql, pdo_mysql, pdo_sqlite, bz2, zip, exif, soap, sockets . The symfony test app worked with apache. Btw. cgi just builds, so i expect it to just work. Nevertheless, several tests are still failing in the core. 

Andrea, there's also a fix for decbin, decoct, dechex. Please check it. I'll touch the tests if you find it right, for now checked manually and the results seem to be correct.

I think we're now steeled to run the tests with realapps. There's a certain instability, but that are almost some edge cases. Also, despite many don't fail, one should inspect whichever places where the bigint needs to be integrated in the extensions. But that is anyway not critical to run the tests because the most impact is in the core, not in the exts. I think it's far enough to run the real life app tests. If they're ok, one can put the further efforts.

Cheers

### CODE REVIEW

**Comment by weltling** [comment]
ups, pdo_pgsql instead of pdo_mysql was the second item )

**Comment by hikari-no-yume** [comment]
You can edit descriptions, you know ;)

**Comment by weltling** [comment]
yeah, just an attitude ... since github sends mails which won't be resent after an edit

**Comment by hikari-no-yume** [comment]
Ah :)

**Comment by hikari-no-yume** [comment]
I merged this but I need to go and fix up decbin/oct/hex, they're a mess (and it's not your fault, they were always a mess, it looks like).

**Comment by weltling** [comment]
Hi Andrea,

thanks for merging. You're right, the current decbin and others is somehow inconsistent. I haven't touched the tests for this reason. The behaviour between the PHP core and GMP/MPIR is somehow different. But I think GMP is doing it more correctly.

All in all, we should be in some testable state now, IMHO. Maybe it'd make sense to announce this. Also testing the remaining exts. There can be open opportunities in the exts now with the new APIs, like handling large ints with databases in 32 bit PHP build. Well, probably not that relevant yet. I'm aware of some still failing tests in the core and the remaining extensions, however it'd make sense to let the people wanted to test to do so. Then one can handle accordingly after some feedbacks are there.

Cheers.

**Comment by hikari-no-yume** [comment]
I decided to revert the `decbin` stuff you did and gave up trying to fix it for now, PHP's base conversion functions are an utter clusterfuck of horribleness that needs to be killed with fire, and I'm _not_ touching them again...

Also, I announced on internals about your work on making more exts build w/ `bigint` :)

**Comment by weltling** [comment]
Hi Andrea,

yeah, that's fine with reverting. Maybe we could later replace them with only GMP or libtommath, not that those are much performance relevant but would be just uniform. But yeah, later, after the whole was merged.

Great, people can test it now. I was testing it again last weekend with the merge of some changes from you and from master, and it was fine. I was going to ask you some when soon anyway about announcing the testability of the bigint :) Lets see anyway what can be done for the further porting, i'll check the status this WE again.

Cheers.

**Pull request merged**
